---
- name: Installation de jenkins
  hosts: srv-jenkins
  become: true
  tasks:
    - name: Mise à jour du système
      shell: sudo apt-get update

    - name: Installation du JDK
      become: true
      shell: apt install openjdk-17-jdk -y

    - name: Installation de Jenkins
      become: true
      shell: |
        sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
        https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
        https://pkg.jenkins.io/debian-stable binary/" | sudo tee \
        /etc/apt/sources.list.d/jenkins.list > /dev/null
        sudo apt-get update
        sudo apt-get install jenkins -y

    - name: Installation de Docker
      become: true
      shell: apt-get install docker.io -y

    - name: Ajout de l'utilisateur au groupe Docker
      become: true
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Installation de Trivy
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - apt-transport-https
        - gnupg
        - lsb-release

    - name: Creation du conteneur SonarQ
      become: true
      shell: docker run -d --name sonar -p 9000:9000 sonarqube:lts-community
