---
- name: Installation de MariaDB et configuration Galera
  hosts: master:worker
  become: true
  tasks:
    - name: Mise à jour du système
      apt:
        update_cache: yes
        upgrade: yes

    - name: Installation de MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Démarrage de MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes

- name: Installation de MariaDB et configuration Galera
  hosts: master
  become: true
  tasks:
    - name: création de fichier
      shell: touch /etc/mysql/conf.d/galera.cnf

    - name: Configuration de Galera sur srv-sql1
      blockinfile:
        path: /etc/mysql/conf.d/galera.cnf
        block: |
          [mysqld]
          binlog_format=ROW
          default-storage-engine=innodb
          innodb_autoinc_lock_mode=2
          bind-address=0.0.0.0
          # Galera Provider Configuration
          wsrep_on=ON
          wsrep_provider=/usr/lib/galera/libgalera_smm.so
          # Galera Cluster Configuration
          wsrep_cluster_name="all_db_cluster"
          wsrep_cluster_address="gcomm://10.8.2.243,10.8.2.242"
          # Galera Synchronization Configuration
          wsrep_sst_method=rsync
          # Galera Node Configuration
          wsrep_node_address="10.8.2.243"
          wsrep_node_name="master"

- name: Installation de MariaDB et configuration Galera
  hosts: worker
  become: true
  tasks:
    - name: création de fichier
      shell: touch /etc/mysql/conf.d/galera.cnf

    - name: Configuration de Galera sur worker
      blockinfile:
        path: /etc/mysql/conf.d/galera.cnf
        block: |
          [mysqld]
          binlog_format=ROW
          default-storage-engine=innodb
          innodb_autoinc_lock_mode=2
          bind-address=0.0.0.0
          # Galera Provider Configuration
          wsrep_on=ON
          wsrep_provider=/usr/lib/galera/libgalera_smm.so
          # Galera Cluster Configuration
          wsrep_cluster_name="all_db_cluster"
          wsrep_cluster_address="gcomm://10.8.2.243,10.8.2.242"
          # Galera Synchronization Configuration
          wsrep_sst_method=rsync
          # Galera Node Configuration
          wsrep_node_address="10.8.2.242"
          wsrep_node_name="worker"

- name: Installation de MariaDB et configuration Galera
  hosts: master:worker
  become: true
  tasks:
    - name: Arrêt de MariaDB sur jen/work1
      systemd:
        name: mariadb
        state: stopped

- name: Nouveau cluster sur master
  hosts: master
  become: true
  tasks:
    - name: Initialisation d'un nouveau cluster Galera sur le master-db
      shell: galera_new_cluster

    - name: Démarrage de MariaDB sur jenkins
      shell: systemctl start mariadb

- name: Démarrage de MariaDB sur worker
  hosts: worker
  become: true
  tasks:
    - name: Démarrage de MariaDB
      systemd:
        name: mariadb
        state: started
        enabled: yes
